### ISSUE TITLE
Subiendo Practica 1 con corecciones a nueva Branch "dev"

### ISSUE THREAD

**Issue by AgustinEsposito29** [AgustinEsposito29/EstrD2023s1#12]

**Comment by lucasljm2001** [comment]
Visto, NO tenes que cerrar los issues vos, lo tengo que hacer yo, para indicarme que arreglaste el error tenes que contestarme en el issue resuelto, por otro lado, todas las correcciones deben estar en la branch master

**Comment by lucasljm2001** [comment]
Corregido
